leftnav:
- identifier: 600aca04-e82b-21c0-deee-a71b47ed8393
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 92cc6b96-e040-a934-7b6a-98f90002ea6f
  name: Lecture Summaries
  pageRef: /pages/lecture-summaries
  weight: 20
- identifier: 60b83b46-2502-adf6-497f-7d641e0e8a24
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: c23b0020-cd10-21f5-0d3c-4bf4f3fdd0db
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: d753994f-13c0-034c-aef6-5b7647bfccb6
  name: Resource Test
  pageRef: /resources/7-344f18
  weight: 50
- identifier: c2c4e056-d418-4d34-a1cd-b18d1a5cb965
  name: Resource List Test
  pageRef: /lists/test-resource-list
  weight: 60
- identifier: 21178308-fef8-42de-b632-0f38e0ea8450
  name: "\u30C6\u30B9\u30C8\u30DA\u30FC\u30B8"
  pageRef: "/pages/\u30C6\u30B9\u30C8\u30DA\u30FC\u30B8"
  weight: 70
